# Generated by Django 4.1.5 on 2023-01-10 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benozy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='category',
            field=models.ManyToManyField(related_name='it', to='benozy.category'),
        ),
    ]
