# Generated by Django 4.1.5 on 2023-01-11 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('benozy', '0003_remove_savingcalc_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savingcalc',
            name='category',
        ),
    ]
