# Generated by Django 4.1.5 on 2023-01-11 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benozy', '0005_remove_savingcalc_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingcalc',
            name='category',
            field=models.ManyToManyField(related_name='item', to='benozy.category'),
        ),
        migrations.AddField(
            model_name='savingcalc',
            name='price',
            field=models.ManyToManyField(related_name='amount', to='benozy.price'),
        ),
        migrations.AlterField(
            model_name='price',
            name='price',
            field=models.IntegerField(),
        ),
    ]
