# Generated by Django 4.1.5 on 2023-01-11 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('benozy', '0006_savingcalc_category_savingcalc_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savingcalc',
            name='price',
        ),
        migrations.DeleteModel(
            name='Price',
        ),
    ]
