# Generated by Django 4.1.5 on 2023-01-11 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benozy', '0007_remove_savingcalc_price_delete_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingcalc',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
