# Generated by Django 4.1.5 on 2023-01-11 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('benozy', '0008_savingcalc_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='title',
        ),
    ]
