# Generated by Django 4.1.5 on 2023-01-11 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benozy', '0010_alter_savingcalc_saved_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingcalc',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='order', to='benozy.category'),
        ),
    ]
