# Generated by Django 4.1.5 on 2023-01-11 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('benozy', '0011_savingcalc_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savingcalc',
            name='items',
        ),
    ]
