# Generated by Django 4.1.5 on 2023-01-11 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benozy', '0012_remove_savingcalc_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savingcalc',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AddField(
            model_name='savingcalc',
            name='category',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
