# Generated by Django 4.1.5 on 2023-01-11 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benozy', '0013_remove_savingcalc_category_delete_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingcalc',
            name='category',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='savingcalc',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
