# Generated by Django 4.1.5 on 2023-01-11 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benozy', '0014_alter_savingcalc_category_alter_savingcalc_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingcalc',
            name='day',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='savingcalc',
            name='month',
            field=models.CharField(max_length=30),
        ),
    ]
